### ISSUE TITLE
Alternative REST API

### ISSUE THREAD

**Issue by Lafudoci** [pybitcash/bitcash#94]
It seems rest.bitcoin.com is so unstable lately. This situation makes my service relied on bitcash lib not usable. Is there any alternative way that I can recover this?

**Comment by merc1er** [comment]
My services are down as well because of this. I am actively looking into a solution (see `insomnia` branch for example), but I think a most efficient solution would be to self host some kind of API.

https://github.com/actorforth/bch-toolkit offers this, but it is not yet ready for mainnet (only works for regtest at this point). Whenever this is ready, we will be switching the main API to it.

**Comment by merc1er** [comment]
#98 fixes this @Lafudoci
